name: "CI"

on:
  push:
    paths:
      - "./ci.yml"
  workflow_dispatch: ~

jobs:
  deps:
    name: "Install depedencies"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - run : ls