name: "CI"

on:
  push:
    paths-ignore:
      - "./ci.yml"
  workflow_dispatch: ~
# faire un job qui install les dépendances et build le projet
jobs:
  deps:
    name: "Install depedencies"
    runs-on: "ubuntu-latest"
    services:
      database:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app
        ports:
          - 3306:3306
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - run : ls
      - name: "Setup PHP 8.1"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: "composer:v2"
      - name: "Check database healthy"
        run: nc -z localhost 3306
      - name: "Install composer dependencies"
        run: |
          export APP_ENV=test
          cd app
          composer install --prefer-dist --no-progress --no-suggest