name: "CI"

on:
  push:
    paths-ignore: "./ci-basics.yml"
  workflow_dispatch: ~

jobs:
  linter:
    name: "Lint code"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Composer install
        uses: php-actions/composer@v6
      - name: "Generate cs config"
        run: cp phpcs.xml.dist phpcs.xml
      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.1
          path: src/
          standard: phpcs.xml
      - name: "PHPStan"
        uses: php-actions/phpstan@v3
        continue-on-error: true
        with:
          path: app/src/
          php_version: 8.1
          level: 9

  deps:
    needs: ["linter"]
    name: "Install depedencies"
    runs-on: "ubuntu-latest"
    services:
      database:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app
          MYSQL_ROOT_HOST: "%"
        ports:
          - 3306:3306
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: 8.1
          tools: composer
      - name: "Check database healthy"
        run: nc -zv localhost 3306
      - name: "Install composer deps"
        run: |
          export APP_ENV=test
          cd app
          composer install --prefer-dist --no-interaction --no-progress
      - name: "Run migrations"
        run: |
          cd app
          php bin/console d:m:m
        env:
          DATABASE_HOST: 127.0.0.1
          DATABASE_NAME: app
          DATABASE_PASSWORD: password
      - name: "Start server"
        run: |
          cd app
          php bin/console
          php -S 127.0.0.1:8080 -t public &
          sleep 2
          nc -zv localhost 8080
      #- name: "Start PHPUnit"
      #  uses: php-actions/phpunit@v3
      - name: "Start PHPUnit"
        run: |
          wget -O phpunit.phar https://phar.phpunit.de/phpunit-10.phar
          chmod +x phpunit.phar
          ./phpunit.phar