name: "CI"

on:
  push:
    branches:
      - master
    paths:
      - "app/**"

jobs:
  hello:
    runs-on: "ubuntu-latest"
    steps:
    - name : "Hello world"
      run : echo "Hello, world!"
    - name: "Multiple Lines"
      run: |
          echo "This is the first line"
          echo "This is the second line"
          echo "This is the third line"
    - name: "List directory"
      run: ls